name: weather_ap
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
   sdk: flutter
  cupertino_icons: ^1.0.2
  fluttericon: 2.0.0
  http: ^1.2.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  url_launcher: ^6.0.14
  url_launcher_web: ^2.2.3
  permission_handler: ^11.2.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  shimmer: ^3.0.0
  mapbox_search: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/house.png
    - assets/clear_night.png
    - assets/day_clear.png
    - assets/clear_day.png
    - assets/average_temp.png
    - assets/high_temp.png
    - assets/low_temp.png
fonts:
  - family: Sunflower
    fonts:
      - assets: assets/fonts/Sunflower-Bold.ttf
      - assets: assetsfonts/Sunflower-Light.ttf
      - assets: assets/fonts/Sunflower-Medium.ttf
